# config
server:
  port: 8081
  env: 0 # 0 test, 1 pro
  log_level: "debug" # debug, info, warning, error
  log_dir: "./"
  show_sql: true
  num_once_limit: 100
  exec_no_backup: false

db:
  address: "127.0.0.1"
  port: 3306
  user: "root"
  password: "aaaaaa"
  db_name: "dbinjection"
  max_idle_conn: 2
  max_open_conn: 30

login:
  ldap:
    host: "ldap.test.com"
    port: 389
    base_dn: "dc=test,dc=com"
    use_ssl: false
    bind_dn: "cn=hi,dc=test,dc=com"
    bind_pwd: "password"
  login_path: "https://ipalfish.com/login"
  token_secret: ""
  token_effective_hour: 1


role:
  from: "admin" # admin or conf
  conf:
    dba:
      - "zhangdashu"
      - "wamgdazhang"
